name: Running Python CI jobs

on:
  push:
    branches:
      - master
    paths:
      - 'app/**'
      - 'tests/**'
      - '.github/workflows/python-lint.yml'

  pull_request:
    paths:
      - 'app/**'
      - 'tests/**'
      - '.github/workflows/python-lint.yml'

jobs:
  python-run:
    runs-on: ubuntu-latest

    steps:
      - name: Get repository
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install yapf pytest pytest-cov

      - name: Lint with yapf
        run: |
          if [ -d app ]; then python -m yapf -ipr app/; fi
          if [ -d tests ]; then python -m yapf -ipr tests/; fi
          test $(git status --porcelain | wc -l) -eq 0 || { git diff; false; }
      
      - name: Test with pytest
        run: |
          pytest tests/ --cov=app